# Generated by Django 3.0.7 on 2020-06-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='diary',
            name='desc',
            field=models.TextField(max_length=100000000000),
        ),
    ]
