# Generated by Django 3.0.7 on 2020-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_diary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='name',
            field=models.CharField(default='juned', max_length=100),
            preserve_default=False,
        ),
    ]
